
# Manipulation de fichiers


# open

Le mode est donné sous la forme d'une chaîne de caractères. Voici les principaux modes :

    'r' : ouverture en lecture (Read).

    'w' : ouverture en écriture (Write). Le contenu du fichier est écrasé. Si le fichier n'existe pas, il est créé.

    'a' : ouverture en écriture en mode ajout (Append). On écrit à la fin du fichier sans écraser l'ancien contenu du fichier. Si le fichier n'existe pas, il est créé.
    

In [1]:
f = open("toto.txt",mode='w')
f.write('yep')

3

# close

Lorsque l'on a fini de manipuler un fichier ouvert, il est normalement necessaire de le fermer, pour liberer les ressources liées à ce fichier

In [2]:
f.close()

# with

La "vraie" maniere de faire consiste a utiliser le mot-clé "with". Ceci evite d'avoir à fermer explicitement le fichier avec close

In [3]:
with open("toto.txt",'r') as f:  # le fichier existe à l'avance sinon error
    print(f.closed) ## closed (et pas 'close') est un marqueur booleen indiquant si le fichier est ouvert ou fermé
print(f.closed)


False
True


# read

In [4]:
### je veux voir le contenu de mon fichier
with open("toto.txt",'r') as f:
    val = f.read() 
print('val : ', val)

val :  yep


tout le contenu du fichier est lu d'un coup

# readlines

In [5]:
# let write a multi line
txt = """yep
yop
yip
"""
with open("toto2.txt",'w') as f:
    f.write(txt)

In [6]:
### je veux voir le contenu de mon fichier ligne par ligne
f = open("toto2.txt",'r')
lines = f.readlines()
f.close()
print(lines)

['yep\n', 'yop\n', 'yip\n']


# Lecture string/bytes et importance de l'encoding (UTF-8)


In [7]:
chaine1 = b"Ceci est une chaine d'octets"

print(chaine1)
print(type(chaine1))
print(chaine1[-1])

chaine2 = "Ceci est une chaine de caractères particuliers 你好 صباح الخير"

print(chaine2)
print(type(chaine2))
print(chaine2[-1])


b"Ceci est une chaine d'octets"
<class 'bytes'>
115
Ceci est une chaine de caractères particuliers 你好 صباح الخير
<class 'str'>
ر


In [8]:
# lets put this 2 object in the same file
with open("chaine.txt",'wb') as f:
    f.write(chaine1)

with open("chaine.txt",'a') as f:
    f.write('\n')
    f.write(chaine2)

In [9]:
with open('chaine.txt', mode= 'r', encoding='utf8') as f:
    txt = f.read()
print(txt, type(txt), len(txt))

Ceci est une chaine d'octets
Ceci est une chaine de caractères particuliers 你好 صباح الخير <class 'str'> 89


In [10]:
with open('chaine.txt', mode='rb') as f:
    b = f.read()
print(b, type(b), len(b))

b"Ceci est une chaine d'octets\nCeci est une chaine de caract\xc3\xa8res particuliers \xe4\xbd\xa0\xe5\xa5\xbd \xd8\xb5\xd8\xa8\xd8\xa7\xd8\xad \xd8\xa7\xd9\x84\xd8\xae\xd9\x8a\xd8\xb1" <class 'bytes'> 103


In [11]:
txt2 = b.decode('utf8')
print(txt2, type(txt2))

Ceci est une chaine d'octets
Ceci est une chaine de caractères particuliers 你好 صباح الخير <class 'str'>


# Sauvegarde et lecture avec numpy : format texte


## loadtxt 

In [12]:
import numpy as np

data = np.loadtxt('./data/Coords.txt') 
print (data)


[[-12.  56.   4.]
 [  6.  50.  12.]
 [  8.  36.   2.]
 [ 24.  24. -18.]
 [-12.  22.  28.]
 [-12.  22.  26.]
 [-32.  20. -18.]
 [-28.  16.  32.]
 [-48.  14.   8.]
 [-10.  10.  44.]
 [-34.   8.  38.]
 [  4.   6.  50.]
 [  4.   6.  50.]
 [ 10.   4.  74.]
 [ -2.   4.  44.]
 [ 24.   4. -10.]
 [ 24.   4. -16.]
 [ 40.   2.  62.]
 [-54.   2.  38.]
 [-26.  -4.  70.]]


## savetxt

In [13]:
data = np.zeros(shape = (1000,1000), dtype = "float32")
print(data)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
np.savetxt("data.txt", data, fmt = "%f")

# Sauvegarde et lecture avec numpy : format .npy, load et save

In [15]:
np.save("data.npy", data)

In [16]:
data2 = np.load("data.npy")
data2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

# Concept d'Arborescence

![Image](./img/mac_tree.png)     ![Image](./img/win_tree.jpg)    ![Image](./img/linux-tree.png)

Racine :

    mac et linux : /
    
    windows : C:\
            


Chemin absolu :
    
    linux : /home/alex/projets/formation_python/
    
    windows : C:\\Users\\alex\\projets\\formation_python\\   (double\ car caractère d'échapement)
    
    mac : /Disque dur/Users/alex/projets/formation_python/

Chemin relatif :

    ./          là ou je suis actuellement
    ../       je remonte d'un dossier par rapport à là ou je suis
    
    idem windows mais avec \
    
    
    exemple : np.loadtxt('./data/Coords.txt') 
    
    

## Le module os (Operating System)



### 1 - Prendre de l'information sur le sysème de fichiers

+ import os


+ os.uname() : infos système


+ os.getcwd() : pour obtenir le répertoire en cours


+ os.path.abspath(path) : retourne une version absolue du chemin path


+ os.path.relpath(path[, start]) : retourne une version relative du chemin path. Par défaut, par rapport au working dir, sinon : spécifier un argument start qui sera le répertoire de base


### 2 - Faire des actions sur le système de fichiers

+ os.chdir(foldername)  : va dans le répertoire spécifié


+ os.mkdir(’mydir’) : crée le répertoire mydir


+ os.rename(oldname, newname) : renomme oldname en newname


+ os.remove(filename) : efface le fichier filename


### 3 - Utilitaires

+ os.path.join(morceau1, morceau2) : colle deux morceaux de chemin ensemble  en utilisant les caractères adaptés au système


+ os.path.expanduser("~") : retourne le chemin vers le répertoire "Home" de l'utilisateur sur la machine


+ os.path.split(racine/nomfichier_ou_rep) : permet de séparer la dernière branche de la racine, résultat sous forme de tuple
    *ex : (filepath, filename) = os.path.split("/Users/admin/Desktop") 
    *filename: "Desktop"


+ os.path.splitext(nomfichier.extension) : sépare le nom de l'extension. Résultat sous forme de tuple


+ os.listdir(path) :  prend un nom de chemin et retourne une liste du contenu du répertoire.


+ os.path.isfile : pour séparer les fichiers des répertoires. (os.path.isdir existe aussi). isfile prend un nom de chemin et :
     *retourne 1 / True si le chemin représente un fichier
     *0 / False dans le cas contraire. 


+ os.walk(top, topdown=True) : à parir de top (repertoire racine), parcourt l'arborescence en descendant si topdown=True, en montant sinon, et renvoie un tuple : (dirpath, dirnames, filenames) qui contient tous les répertoires dirnames rencontrés avec les fichiers filenames qui s'y trouvent

>for dossier, sous_dossiers, fichiers in os.walk('/tmp/test'):

>        for fichier in fichiers:

>            print(os.path.join(dossier, fichier))

In [17]:
import os
os.listdir('./')

['file_manipulation.ipynb',
 'data',
 'mafigure.svg',
 'loop_index_slice.ipynb',
 'matplotlib_base.ipynb',
 'data.txt',
 'img',
 'numpy_indexing.ipynb',
 'numpy_advanced.ipynb',
 'Base_language.ipynb',
 'numpy_base.ipynb',
 'scipy_overview.ipynb',
 'toto.txt',
 '.ipynb_checkpoints',
 'data.npy',
 'toto2.txt',
 'Data_exo_final',
 'chaine.txt']

## Le module pathlib = nouvelle méthode

In [18]:
from pathlib import Path

home = Path.home()
home


PosixPath('/home/samuel')

In [19]:
ici = Path('.').absolute()
ici

PosixPath('/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks')

In [20]:
doc = home / 'Documents'
doc

PosixPath('/home/samuel/Documents')

In [21]:
for item in Path('/').iterdir():
    print(item)

/run
/boot
/vmlinuz
/lib
/tmp
/home
/opt
/mnt
/lost+found
/media
/snap
/etc
/root
/usr
/sys
/initrd.img
/dev
/srv
/bin
/data_sorting
/initrd.img.old
/libx32
/cdrom
/swapfile
/lib32
/var
/vmlinuz.old
/proc
/lib64
/sbin


In [22]:
file_path = Path('/home/samuel/Figure_1.png')

print(file_path.is_file())

print(file_path.stem)
print(file_path.suffix)
print(file_path.parent)
print(file_path.parents[0])
print(file_path.parents[1])
print(file_path.parents[2])



True
Figure_1
.png
/home/samuel
/home/samuel
/home
/


In [23]:
ici = Path('.').absolute()

for file in ici.glob('*.ipynb'):
    print(file)

/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/file_manipulation.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/loop_index_slice.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/matplotlib_base.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/numpy_indexing.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/numpy_advanced.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/Base_language.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/numpy_base.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/scipy_overview.ipynb


In [24]:
# recursif
for file in Path('/home/samuel/Bureau').glob('**/*.ipynb'):
    print(file)


/home/samuel/Bureau/spikeinterface-motion-estimation.ipynb
/home/samuel/Bureau/drift_estimate_nx32.ipynb
/home/samuel/Bureau/work_with_neuropixels.ipynb
/home/samuel/Bureau/fitting.ipynb
/home/samuel/Bureau/drift_estimate_np128.ipynb
/home/samuel/Bureau/generate_np128_nonrigid_drift.ipynb
/home/samuel/Bureau/motion-estimation-thomas-rigid.ipynb
/home/samuel/Bureau/spikeinterface_motion_estimation.ipynb
/home/samuel/Bureau/generate_nx32_nonrigid_drift.ipynb
/home/samuel/Bureau/motion-estimation-thomas-non-rigid.ipynb
/home/samuel/Bureau/demo_si_micmac/demo_spikeinterface.ipynb
/home/samuel/Bureau/demo_si_micmac/study_noise_across patient.ipynb


## exercice 1

Faire un script pour explorer le dossier 'data/data_folder'

Lire les datas dans une structure hierachique adaptée (dict/list/array)



## solution 1

In [25]:
folder = Path('data/data_folder')

mydata = {}
for file_path in folder.glob('**/*.npy'):
    subject = file_path.parents[0].stem
    session = int(file_path.stem.replace('session_', ''))
    if subject not in mydata:
        mydata[subject] = {}
    arr = np.load(file_path)
    mydata[subject][session] = arr
    
mydata


{'UJ03': {4: array([[ 1.58631923, -0.72739628, -0.26158817],
         [ 2.56425695,  1.13199062,  0.54568674],
         [-0.49778992,  1.4074506 , -0.4162464 ],
         [ 1.55625927,  0.60217849,  0.3552943 ]]),
  3: array([[ 2.52932469,  1.68744126,  1.94924154],
         [ 0.86571286,  0.87198381,  0.18029687],
         [ 2.25554749, -1.07055761, -0.48938934],
         [ 1.7422904 , -0.10962135,  1.14372104]]),
  2: array([[ 0.39786945,  0.61703221,  0.15183394],
         [-0.43560855, -0.35867696,  1.34792642],
         [ 1.2627654 , -1.01953818,  1.44585437],
         [ 0.89007494,  0.61240892,  0.02416696]]),
  1: array([[ 2.22818769, -0.50955824,  0.03992623],
         [ 0.41742752, -2.01602787, -0.21802683],
         [ 0.47037164,  0.74212077,  0.34622762],
         [ 0.77117791, -2.02967243, -0.57107898]]),
  5: array([[-1.45133283, -1.40125602, -1.99980305],
         [ 0.10602695,  0.43662809, -0.22712406],
         [ 0.52926951,  0.56603048, -1.72214415],
         [-0.679310