# numpy fancy indexing

Numpy permet de manipuler des sous ensemble d'un tableau en lecture/écriture.

Il y a 4 grandes methodes:
  * scalaire
  * par *'slice'*
  * par condition booléene
  * par list d'index



In [3]:
import numpy as np

# reshape

In [4]:
a = np.arange(24) #### equivalent du range, mais pour generer des ndarray
print(a)
print(a.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [5]:

a2 = a.reshape(6,4) ### des lignes de 4 elements, et on a 6 lignes
print(a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [6]:
a3 = a.reshape(4,2,3)
print(a3.shape)
print(a3)

(4, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


Avec dimension joker= -1

-> la dimension "joker" vaut le "reste" des dimensions restantes

In [7]:
a3 = a.reshape(4,-1,3)
print(a3.shape) ### la dimension par default vaut ici (24/4)/3 = 2



(4, 2, 3)


# Lecture/écriture d'un seul élément

In [8]:
a = np.arange(12).reshape(4,3)
print (a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# zeros based
# ligne colonne 
e = a[1,1]


print(e)



4


en fait pas vraiment, depent plutot des dimensions que l'on a donné
Dans les visus de ndarray, la derniere dimension apparait toujours le nombre des valeurs comme une ligne (~ colonne), la dimension suivante apparait comme le nombre de lignes  


In [10]:
a[1,2] = 1000
a

array([[   0,    1,    2],
       [   3,    4, 1000],
       [   6,    7,    8],
       [   9,   10,   11]])

# Par slice

![title](img/slice.jpeg)

In [11]:
# ne pas comprendre ça 
# regle du broadcast 
#https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
b = np.arange(6).reshape(1,6) 
print(b)
c = 10*np.arange(6).reshape(6, 1)
print(c)
a = b + c
print(a)

[[0 1 2 3 4 5]]
[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [12]:
a2 = a[3:, 0:5:2]
a2

array([[30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

# Par mask boolean

In [13]:
a = np.random.randn(15)
a

array([ 0.34673449,  1.42426928,  0.99963903, -0.99031362, -1.3432432 ,
        1.52973512,  1.14409893, -0.18694738, -1.10449459,  1.51059399,
       -0.66729073,  1.5680808 ,  1.51659913, -0.86753859, -1.60905033])

On peut créer un vecteur de booléen facile, et l'utiliser ensuite pour selectioner un sous ensemble.

In [14]:
keep = (a>0.)
keep
print(keep)
not_keep = ~keep # not en boolean (existe aussi np.logical_not)
print(not_keep)


[ True  True  True False False  True  True False False  True False  True
  True False False]
[False False False  True  True False False  True  True False  True False
 False  True  True]


In [15]:
a3 = a[keep]
a3

array([0.34673449, 1.42426928, 0.99963903, 1.52973512, 1.14409893,
       1.51059399, 1.5680808 , 1.51659913])

# Selection explicite d'une liste

In [16]:
a = np.arange(7)*10
a

array([ 0, 10, 20, 30, 40, 50, 60])

In [17]:
l = [2, 4, 0]
a2 = a[l]
a2

array([20, 40,  0])

# Attention une slice pointe sur le même tableau!!

Un tableau issue d'un même tableau est une *'view'*.



In [18]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a2 = a[2:-2]
a2[0:6] = np.arange(6)*-10
a2

array([  0, -10, -20, -30, -40, -50])

In [21]:
a


array([  0,   1,   0, -10, -20, -30, -40, -50,   8,   9])


Sinon il faut faire une copie explicite.

In [25]:
a = np.arange(10)
a2 = a[2:-2].copy()
a2[0:6] = np.arange(6)*-10
a2

array([  0, -10, -20, -30, -40, -50])

# Exercice 1

A partir du numpy array suivant
```
table = np.array([[1, 10,  1, 11],
                  [2, 21,  2, 20],
                  [3, 30, 3, 31],
                  [4, 41, 4, 40]])
```

créer 4 numpy array :
* table_0 : avec tous les élément plus grand que 10. Utiliser des slices.
* table_1 : tous les élément plus petit que 10 et impaires. Utiliser des slices.
* table_2 : tous les élément plus grand que 10 et impaires. Peut on utiliser des slices ?

In [31]:
#my_table = np.random.randint(0,4,(4,4))
table = np.array([[1, 10,  1, 11],
                 [2, 21,  2, 20],
                 [3, 30, 3, 31],
                 [4, 41, 4, 40]])
print(table)


[[ 1 10  1 11]
 [ 2 21  2 20]
 [ 3 30  3 31]
 [ 4 41  4 40]]


# Solution 1

# Exercie 2
Voici un vecteur
a = np.random.randn(5000)
créer un vecteur b qui enlève les déviants.

M + 2.5*std
M - 2.5*std

note : np.mean(a) donne la moyenne de a et np.std(a) donne l'écart-type de a





# Solution 2

# nan = not a number

In [43]:
a = np.arange(5, dtype='float64')
a[2] = np.nan
a

array([ 0.,  1., nan,  3.,  4.])

In [44]:
b = np.exp(1e40)
b

/tmp/ipykernel_8961/4029968746.py:1: RuntimeWarning: overflow encountered in exp
  b = np.exp(1e40)


inf

# test : np.isinf et np.isnan




In [46]:
np.isinf(b)

True

In [47]:
np.isnan(a)

array([False, False,  True, False, False])